tasks:
  - name: Install AWS CLI
    init: |
      sudo apt-get update
      sudo apt-get install -y curl unzip
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
    env:
      AWS_CLI_AUTO_PROMPT: on-partial

vscode:
  extensions:
    - 42Crunch.vscode-openapi




# tasks:
#   - name: aws-cli
#     env:
#       AWS_CLI_AUTO_PROMPT: on-partial
#       init: |
#         cd /workspace
#         curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#         unzip awscliv2.zip
#         sudo ./aws/install
#         cd $THEIA_WORKSPACE_ROOT
# vscode:
#   extensions:
#     - 42Crunch.vscode-openapi